# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UD Turkic Workshop 2025
description: > # ignore newlines until "baseurl:"
  This is the webpage of the workshop on Universal Dependencies annotation standards and practices for the Turkic Languages held in conjunction with the SyntaxFest 2025 in Ljubljana, Slovenia.
baseurl: "/udtw25"
github_username: ud-turkic
encoding: utf-8
future: true

# Build settings
markdown: kramdown
